import type { Vehicule } from "./types";

// Source temporaire : mock data en attendant le branchement du sync CardiffVO.
// Le worker scripts/sync-cardiff.mjs viendra remplir cette liste depuis la base Postgres.

const PIC = (seed: string, i: number) =>
  `https://picsum.photos/seed/${seed}-${i}/1200/800`;

export const vehicules: Vehicule[] = [
  {
    id: 1,
    vin: "VF1RFD00X12345678",
    slug: "renault-clio-v-345678",
    marque: "Renault",
    modele: "Clio V",
    version: "1.0 TCe 90 Intens",
    annee: 2021,
    carrosserie: "Berline",
    couleurExt: "Gris Titanium",
    couleurInt: "Tissu noir",
    energie: "Essence",
    boite: "Manuelle",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 5,
    puissanceReel: 90,
    dateMec: "2021-04-15",
    kilometrage: 42500,
    kmGaranti: true,
    premiereMain: true,
    garantieDuree: "6 mois",
    garantieLibelle: "Garantie 6 mois pièces et main d'œuvre",
    prixTtc: 13990,
    co2: 117,
    critAir: "1",
    commentairePublic:
      "Clio 5 1.0 TCe en très bel état, entretien à jour, climatisation automatique, GPS, caméra de recul.",
    equipSerie: ["Climatisation automatique", "Régulateur de vitesse", "ABS", "ESP", "Bluetooth"],
    equipOption: ["GPS", "Caméra de recul", "Apple CarPlay"],
    equipPerso: [],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 3 * 86400000).toISOString(),
    photos: [PIC("clio", 1), PIC("clio", 2), PIC("clio", 3), PIC("clio", 4)],
    alaune: true
  },
  {
    id: 2,
    vin: "WVWZZZ16ZAW123456",
    slug: "volkswagen-golf-7-123456",
    marque: "Volkswagen",
    modele: "Golf 7",
    version: "1.6 TDI 110 BlueMotion Confortline",
    annee: 2017,
    carrosserie: "Berline",
    couleurExt: "Blanc Pur",
    energie: "Diesel",
    boite: "Manuelle",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 6,
    puissanceReel: 110,
    dateMec: "2017-09-02",
    kilometrage: 98300,
    kmGaranti: true,
    premiereMain: false,
    garantieDuree: "6 mois",
    prixTtc: 12490,
    co2: 99,
    critAir: "2",
    commentairePublic:
      "Golf 7 phase 2, bien entretenue, factures à l'appui. Diesel économique, idéale longs trajets.",
    equipSerie: ["Climatisation", "Régulateur", "ABS", "ESP", "Bluetooth", "Start & Stop"],
    equipOption: ["Pack Confort", "Vitres surteintées"],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 20 * 86400000).toISOString(),
    photos: [PIC("golf", 1), PIC("golf", 2), PIC("golf", 3)],
    alaune: true
  },
  {
    id: 3,
    vin: "VF7N7HMZ6JJ123456",
    slug: "peugeot-208-ii-123456",
    marque: "Peugeot",
    modele: "208 II",
    version: "PureTech 100 Allure",
    annee: 2022,
    carrosserie: "Berline",
    couleurExt: "Bleu Vertigo",
    energie: "Essence",
    boite: "Automatique",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 5,
    puissanceReel: 100,
    dateMec: "2022-06-10",
    kilometrage: 28900,
    kmGaranti: true,
    premiereMain: true,
    garantieDuree: "6 mois",
    prixTtc: 17490,
    co2: 121,
    critAir: "1",
    commentairePublic:
      "208 Allure boîte automatique EAT8, équipement complet, parfait état général.",
    equipSerie: ["i-Cockpit 3D", "Climatisation auto", "Régulateur adaptatif"],
    equipOption: ["GPS connecté", "Caméra de recul", "Apple CarPlay"],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 1 * 86400000).toISOString(),
    photos: [PIC("p208", 1), PIC("p208", 2), PIC("p208", 3), PIC("p208", 4)],
    alaune: true
  },
  {
    id: 4,
    vin: "JTDKGNEC30N123456",
    slug: "toyota-yaris-iv-123456",
    marque: "Toyota",
    modele: "Yaris IV",
    version: "Hybride 116h Design",
    annee: 2021,
    carrosserie: "Berline",
    couleurExt: "Rouge Chili",
    energie: "Hybride",
    boite: "Automatique",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 4,
    puissanceReel: 116,
    dateMec: "2021-11-23",
    kilometrage: 35200,
    kmGaranti: true,
    premiereMain: true,
    garantieDuree: "6 mois",
    prixTtc: 18990,
    co2: 92,
    critAir: "1",
    commentairePublic: "Yaris Hybride très peu polluante, consommation 4L/100, équipement Design complet.",
    equipSerie: ["Toyota Safety Sense", "Climatisation auto", "Caméra de recul"],
    equipOption: ["Pack Design", "Jantes alu 17"],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 12 * 86400000).toISOString(),
    photos: [PIC("yaris", 1), PIC("yaris", 2)],
    alaune: true
  },
  {
    id: 5,
    vin: "WAUZZZ8V2HA123456",
    slug: "audi-a3-sportback-123456",
    marque: "Audi",
    modele: "A3 Sportback",
    version: "35 TDI 150 S tronic S line",
    annee: 2019,
    carrosserie: "Berline",
    couleurExt: "Noir Mythic",
    energie: "Diesel",
    boite: "Automatique",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 8,
    puissanceReel: 150,
    dateMec: "2019-03-18",
    kilometrage: 68400,
    kmGaranti: true,
    premiereMain: false,
    garantieDuree: "6 mois",
    prixTtc: 21490,
    co2: 110,
    critAir: "2",
    commentairePublic: "A3 S line, finition haut de gamme, S tronic, sièges sport, GPS MMI.",
    equipSerie: ["Climatisation auto bizone", "MMI Navigation", "Bluetooth", "Virtual Cockpit"],
    equipOption: ["Pack S line", "Sièges chauffants", "Jantes 18\""],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 6 * 86400000).toISOString(),
    photos: [PIC("a3", 1), PIC("a3", 2), PIC("a3", 3), PIC("a3", 4), PIC("a3", 5)]
  },
  {
    id: 6,
    vin: "VF3LBHZJ0KS123456",
    slug: "citroen-c3-aircross-123456",
    marque: "Citroën",
    modele: "C3 Aircross",
    version: "PureTech 110 Shine",
    annee: 2020,
    carrosserie: "SUV",
    couleurExt: "Blanc Banquise",
    energie: "Essence",
    boite: "Manuelle",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 6,
    puissanceReel: 110,
    dateMec: "2020-05-30",
    kilometrage: 52600,
    kmGaranti: true,
    premiereMain: true,
    garantieDuree: "6 mois",
    prixTtc: 14490,
    co2: 121,
    critAir: "1",
    commentairePublic: "C3 Aircross Shine, intérieur spacieux, idéale famille.",
    equipSerie: ["Climatisation auto", "Régulateur", "Aide stationnement"],
    equipOption: ["Toit bi-ton", "Pack Couleur"],
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 30 * 86400000).toISOString(),
    photos: [PIC("c3a", 1), PIC("c3a", 2)]
  },
  {
    id: 7,
    vin: "VF1KJ8009L9123456",
    slug: "renault-zoe-r135-123456",
    marque: "Renault",
    modele: "Zoé",
    version: "R135 Intens",
    annee: 2020,
    carrosserie: "Berline",
    couleurExt: "Bleu Céladon",
    energie: "Électrique",
    boite: "Automatique",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 4,
    puissanceReel: 135,
    dateMec: "2020-09-12",
    kilometrage: 38500,
    kmGaranti: true,
    premiereMain: true,
    garantieDuree: "6 mois",
    prixTtc: 13990,
    co2: 0,
    critAir: "0",
    commentairePublic: "Zoé R135 batterie achetée (non locative), autonomie réelle ~300 km.",
    equipSerie: ["Climatisation auto", "GPS R-Link", "Caméra de recul"],
    equipOption: ["Pack Hiver", "Câble Type 2"],
    soh: 92,
    autonomie: 300,
    capaciteBat: 52,
    tempsRecharge: "9h sur prise renforcée / 50 min en DC 50 kW",
    statut: "disponible",
    dateArrivee: new Date(Date.now() - 5 * 86400000).toISOString(),
    photos: [PIC("zoe", 1), PIC("zoe", 2), PIC("zoe", 3)]
  },
  {
    id: 8,
    vin: "WBA8E5G50H1234567",
    slug: "bmw-serie-3-1234567",
    marque: "BMW",
    modele: "Série 3",
    version: "318d 150 Lounge",
    annee: 2018,
    carrosserie: "Berline",
    couleurExt: "Gris Mineral",
    energie: "Diesel",
    boite: "Automatique",
    nbPortes: 4,
    nbPlaces: 5,
    puissanceFisc: 8,
    puissanceReel: 150,
    dateMec: "2018-02-08",
    kilometrage: 112400,
    kmGaranti: true,
    garantieDuree: "6 mois",
    prixTtc: 16490,
    co2: 112,
    critAir: "2",
    commentairePublic: "318d boîte auto, finition Lounge, sièges cuir.",
    equipSerie: ["Cuir Dakota", "Climatisation auto", "GPS Pro", "Bluetooth"],
    equipOption: ["Pack Lounge"],
    statut: "vendu",
    dateArrivee: new Date(Date.now() - 60 * 86400000).toISOString(),
    dateSortie: new Date(Date.now() - 10 * 86400000).toISOString(),
    photos: [PIC("bmw3", 1), PIC("bmw3", 2)]
  },
  {
    id: 9,
    vin: "VF3DBHMZ8KS123456",
    slug: "peugeot-3008-ii-vendu-123456",
    marque: "Peugeot",
    modele: "3008 II",
    version: "BlueHDi 130 EAT8 Allure",
    annee: 2019,
    carrosserie: "SUV",
    couleurExt: "Gris Platinium",
    energie: "Diesel",
    boite: "Automatique",
    nbPortes: 5,
    nbPlaces: 5,
    puissanceFisc: 7,
    puissanceReel: 130,
    dateMec: "2019-07-04",
    kilometrage: 84200,
    kmGaranti: true,
    garantieDuree: "6 mois",
    prixTtc: 18990,
    co2: 119,
    critAir: "2",
    commentairePublic: "3008 Allure, équipement complet.",
    equipSerie: ["i-Cockpit", "Climatisation auto", "GPS connecté"],
    statut: "vendu",
    dateArrivee: new Date(Date.now() - 90 * 86400000).toISOString(),
    dateSortie: new Date(Date.now() - 20 * 86400000).toISOString(),
    photos: [PIC("3008", 1), PIC("3008", 2)]
  }
];

export function getVehicules(): Vehicule[] {
  return vehicules.filter((v) => v.statut === "disponible" || v.statut === "reserve");
}

export function getVendus(): Vehicule[] {
  return vehicules
    .filter((v) => v.statut === "vendu")
    .sort((a, b) => (b.dateSortie ?? "").localeCompare(a.dateSortie ?? ""));
}

export function getVehiculeBySlug(slug: string) {
  return vehicules.find((v) => v.slug === slug);
}

export function getSimilaires(v: { id: number; modele: string; prixTtc: number }): Vehicule[] {
  return getVehicules()
    .filter((x) => x.id !== v.id)
    .map((x) => ({ x, score: Math.abs(x.prixTtc - v.prixTtc) + (x.modele === v.modele ? -5000 : 0) }))
    .sort((a, b) => a.score - b.score)
    .slice(0, 4)
    .map((p) => p.x);
}
